### ISSUE TITLE
Ytuner  1.1.0 problem with Spaces

### ISSUE THREAD

**Issue by Schaakxs** [coffeegreg/YTuner#12]
Installed v1.1.0 for used with my Yamaha RX-v673.
Great project, but…

when there is a space in the name of A catagory like in ‘The Netherlands’ then the cat wil not show.

For own entries in stations.ini or stations.yaml and in the radio browser sub categories also.

harrie

**Comment by TheBossME** [comment]
Hi Harrie, I do use yaml format like this, without issues.

Just Jazz Radio:
  Al Jarreau: http://drive.uber.radio/uber/jjraljarreau/icecast.audio
  Amy Winehouse: http://drive.uber.radio/uber/jjramywinehouse/icecast.audio

Regards Beatrice

**Comment by Schaakxs** [comment]
I use the Linux app on a virtual machine (debian) on DSM 7

**Comment by coffeegreg** [comment]
Hi Harrie,
Yes, you're right. There is problem with RX-V673 while RX-V671 works properly.
A small problem with space encoding on RX-V673. Fix is on the way ... hang on ...
Thanks for bug reporting.
Greg

**Comment by Schaakxs** [comment]
Top !

**Comment by coffeegreg** [comment]
New 1.1.1 release ready to go. Please try it and have fun :+1:

**Comment by coffeegreg** [comment]
Additionally, I compared the speed of RX-V673 and RX-V671 and it turns out that RX-V671 is much faster. I also noticed that the RX-V673 does not show the station logo when it is selected in the list but not selected for listening.
If a category in Radio-browser turns out to be empty and we want to enter it, the RX-V673 displays "Access error" but the RX-V671 displays correct information about empty content. With the caching option, empty categories are deleted when you try to access them. In this case RX-V671 immediately refreshes such a list, RX-V673 does not (you need to go to the directory above and select the category again). Although the RX-V673 displays 8 stations per page, it queries 10 (!?) and additionally 10 stations preceding the selected station in the selected category. Strange behavior ..
Use YTuner with cache option available since version 1.1.0. This should speed up your RX-V673. Look at attached `avr.ini.example` and read it carefully as well as `ytuner.ini`. :musical_note:

**Comment by TheBossME** [comment]
Hi Greg, 

What changes are implemented.. now my DSP-z7 runs soooo smoothly 👍🙏🙋‍♀️

Regards 
Beatrice

**Comment by coffeegreg** [comment]
Hi Beatrice,

Almost nothing has changed but this "almost nothing" is a lot of for RX-V673. :wink: See for yourself : https://github.com/coffeegreg/YTuner/commit/0159a99b17d70f9bfee9c74368ef7c8a433c4320

`ytuner.ini` file is still v1.1.0 and has an independent version number from the YTuner application version.

Hmm ... interesting thing with this DNS case. :thinking:  Have you used `dnsmasq` before? I didn't use `dnsmasq` at all because I think the DNS Service built into YTuner works great.

I do not know what to think about it. :thinking:  I think you should observe how your Yamaha works now and maybe the conclusions will come by themselves. It may also be possible that the firmware of your DSP-Z7 has some memory or performance issues and sometimes "freeze" happens... or just the internal AVR's CPU is too slow or work with low internal memory. (@Larsvb0 mentioned about his/her Denon here https://github.com/coffeegreg/YTuner/issues/11#issuecomment-1857488854)

Thanks for sharing this insight. It may be helpful for someone else :+1: and of course I'm glad that YTuner _"runs soooo smoothly"_ :smiley:

**Comment by Schaakxs** [comment]
Hi Greg,

thanks for your fast reaction.

I use a Yamaha RX-V673 with firmware 1.96
I use 4 ways to control it: 
 - Yamaha App 5.60 build 1897 (b2d96447) on iPad (ios 16.7.3)
 - Yamaha App 5.60 build 1309 (8d7217de) on S22 (Android 14 )
 - http on port 80 of te receiver
 - via RCU (and Tv screen)
My DNS resolver points vtuner to my yserver (virtual) machine.

You said:
Additionally, I compared the performance of RX-V673 and RX-V671 and it turns out that RX-V671 is much faster. I also noticed that the RX-V673 does not show the station logo when it is selected in the list but not selected for listening.
-> till now i did not look at any logo. But sometimes it looks like it takes a time to display it.

Although the RX-V673 displays 8 stations per page
-> both apps use 11 items on the display. the box indeed 8. Of course i can not see wich requests the receiver makes.

Use YTuner with cache option available since version 1.1.0. This should speed up your RX-V673. Look at attached avr.ini.example and read it carefully as well as ytuner.ini
-> I use the cache option (for logo's?). I cant not find cache entries in avr.ini example!  Ytuner has no perormance issues here. 
-> It performance is better then with vtuner!

**I tested on 1.1.1 now. The bug has gone!
Thank you.** 

By the way: is there a reason why there is no possibility to use https and http as they are mentioned in the stations url?

Harrie
The Netherlands

**Comment by coffeegreg** [comment]
Hi Harrie
>       My DNS resolver points vtuner to my yserver (virtual) machine.
You can also use the built-in DNS service in YTuner. It works pretty fast :rocket: Look at `ytuner.ini` file and `[DNSServer] `section.
One comment above Betrice suggests this might speed things up
> 
> 
> You said: Additionally, I compared the performance of RX-V673 and RX-V671 and it turns out that RX-V671 is much faster. I also noticed that the RX-V673 does not show the station logo when it is selected in the list but not selected for listening. -> till now i did not look at any logo. But sometimes it looks like it takes a time to display it.

Yes. RX-V671 need 3 seconds to display station logo while RX-V673 needs aprox. 10s. But it's not a problem. This just goes to show how differently our AVRs are built inside, even though the model number is slightly different.

> 
> Although the RX-V673 displays 8 stations per page -> both apps use 11 items on the display. the box indeed 8. Of course i can not see wich requests the receiver makes.

Yes, you can. Enable `MessageInfoLevel=4` (`Debug` level) with `ytuner.ini` and start browsing stations with you AVR and look at YTuner's messages meanwhile.

> 
> Use YTuner with cache option available since version 1.1.0. This should speed up your RX-V673. Look at attached avr.ini.example and read it carefully as well as ytuner.ini -> I use the cache option (for logo's?). I cant not find cache entries in avr.ini example! Ytuner has no perormance issues here. -> It performance is better then with vtuner!

`avr.ini` (common for all your AVRs) or something like `feb9a58648c4b9cd61d7ac0a0a653104.ini` (dedicated to a specific AVR - if you own more then one) contains only configuration values for user's filtering (look at `CommonAVRini` setting of `ytuner.ini`). You can filter out some exotic stations that you are not interested in or those that use codecs that your AVR does not support and you want to avoid a message like `Access Error`. Yeah... RX-V673 supports AAC but RX-V671 not :disappointed: (I guess I need to think about the AAC to MP3 on-the-fly transcoding YTuner feature)

The cache option I wrote about is located in the section `[Radiobrowser]` of the `ytuner.ini`. Pay attention of options: `RBCacheType` and `RBCacheTTL`. Better yet, familiarize yourself with all the options available in the `ytuner.ini` and `avr.ini` files. Read their content carefully and control your YTuner according to your needs.
Of course stations logo cache option `IconCache` is usefull as well. :rocket: 
> 
> **I tested on 1.1.1 now. The bug has gone! Thank you.**

It's nice to know that my work is appreciated. :smiley: 
> 
> By the way: is there a reason why there is no possibility to use https and http as they are mentioned in the stations url?

This is possible. Read `[Configuration]` section of `avr.ini` and `Protocol` setting but beware ... As far as I know our RX-V673 does not support SSL/TLS so you'll get "Access Error" message. That's why most of URLs are "s" stripped from "https" to stay as unencrypted "http". Once again, read content of *.ini files carefully and may the sound be with you. :notes: :+1: 

> 
> Harrie The Netherlands

**Comment by Schaakxs** [comment]
Hi Greg,

> this is possible. Read [Configuration] section of avr.ini

Reading is difficult :) I had to leave it blank.

> As far as I know our RX-V673 does not support SSL/TLS 

It looks you are right.  But i had only one channel with https only. So no problem.

> You can also use the built-in DNS service in YTuner.

But i have more 'replacements' then only vtuner.com. So i am happy with the dns reolver option on my pfSense.

**Thanks a lot again.**

For now it is ok. I gonna make ytuner start automatic when my virtual machine boots (i am not a linux expert).

Maybe for the future: it would be nice if there was a setting in config.ini like:
[MyStations]
;entryname=My stations
entryname=This is the text i want to see

and

[Radiobrowser]
;entryname=Radio browser
entryname=Alle radio stations van de wereld

Thanks,
Harrie

**Comment by coffeegreg** [comment]
> Maybe for the future: it would be nice if there was a setting in config.ini like: [MyStations] ;entryname=My stations entryname=This is the text i want to see

Yes. It can be done, but... that's another option to set. And who would want to read about it when "_reading is difficult_" :wink: 
> [Radiobrowser] ;entryname=Radio browser entryname=Alle radio stations van de wereld

Life is too short to go through all those stations available via the radio-browser.info :wink:  .. but ... yes ... customization of main categories/folders. Maybe some day ... :thinking: 
I think I can close this issue. :+1:
