### ISSUE TITLE
Change port not working

### ISSUE THREAD

**Issue by Larsvb0** [coffeegreg/YTuner#25]
Hi Greg, hope you are still working on this.

As you know I am running this in docker (but I have tried this with Windows version as well). I am trying to change the default port 80 to 8020 so I can run another container with a webserver on port 80.

In Ytuner.ini I changed this:
;Web server TCP port. Don't change it if it's not necessary. ; Default = 80
WebServerPort=8020

For the docker images I changed this in Dockerfile:
# Make the TCP/UDP ports to outside the container.
EXPOSE 8020/tcp

I run with HOST network: docker run --name Ytuner --network host -v YTuner:/app/host-shared ytuner:1.2.2

When I try to approach http://10.0.0.12:8020/ I get:Dbg : Unknown route : GET /.
So it seems to be responding

I set up a Reverse Proxy so http://denon.vtuner.com is pointing to 10.0.0.12:8020
When I try to approach http://denon.vtuner.com I get:Dbg : Unknown route : GET /.
So it seems to be responding as well

However the Denon receiver is only playing the known favorites. (I can see responds coming from Ytuner as well)
My Stations show empty list. 

Any ideas?

Same for the Windows version. 
In Ytuner.ini I changed this:
WebServerPort=8020

I set up a Reverse Proxy so http://denon.vtuner.com is pointing to 10.0.0.12:8020

Same problem. 

When quering the Station list I get tis:
13-5-2024 14:44:05 : Dbg : GET /setupapp/denon/asp/browsexm2/loginXML.asp?mac=0CEF23DA75BEE0D17F10B7F74274D2AF&fver=1.754333&dlang=eng&startitems=1&enditems=10.

**Comment by coffeegreg** [comment]
>Hi Greg, hope you are still working on this.

Hi @Larsvb0. Not really, there is very little interest in YTuner project. Everything I wanted to add to YTuner was already added and working as expected, so I moved on to other interesting projects. Of course, I'm not abandoning YTuner...
Now, Let's check out your case ...

Only during the first connection, the AVR communicates with the `vtuner.com` domain and is "redirected" to the YTuner web service. After that, YTuner generates information for the AVR based on its own IP address. Due to this, the AVR will later try to reach your address `10.0.0.12` but using port `80`.
The key to success is the `IPAddress` parameter in the `Configuration` section.
I believed that YTuner should communicate with AVR based on IPv4 addressing (not DNS resolved names) and carefully check its existing IPv4 interfaces to avoid confusion with what the user might enter in `IPAddress` option of `ytuner.ini` file. This concept works great in most cases, but not all, especially when using proxy solution or Docker containers where each container has its own IP address based on `172.17.0.0/16` subnet (with default settings). That's why I used `--network host` option in DOCKER.md file.
I've been aware of this little limitation for a long time and thought no one would encounter it, but now I think I'll change/remove these restrictions on IP checking on existing interfaces. I'll think a little bit whether it would be better to change/remove these restrictions or add a new option, e.g. `HostName`, which the user will be able to use to make YTuner generate information for AVR using this new option value.

Adding this new option will be very simple and when I find some free time in the coming days, I will do it.
I think this should solve your case and prevent others like this from happening in the future.

**Comment by Larsvb0** [comment]
that would be great Greg, really appreciate it and I'll buy you a beer! 

Be aware of the following.
If I use the Windows version and run the webserver on a different port, the result is that it is also not working.

Here is what I do on my laptop (IP=10.0.0.12):
1. in Ytuner.ini make the following change

[WebServer]
;Web server IP address. Don't change it if it's not necessary. ; "default" mean the same value as entered in IPAddress in Configuration section above.
WebServerIPAddress=10.0.0.12

;Web server TCP port. Don't change it if it's not necessary. ; Default = 80
WebServerPort=8020

2. Start Ytuner, it displays it runs on 8020.
3. Create a Reverse Proxy rule so http://denon.vtuner.com/ is pointing to 10.0.0.12:8020

When I try to approach http://denon.vtuner.com/ I get:Dbg : Unknown route : GET /.
When quering the Station list I get this:
13-5-2024 14:44:05 : Dbg : GET /setupapp/denon/asp/browsexm2/loginXML.asp?mac=0CEF23DA75BEE0D17F10B7F74274D2AF&fver=1.754333&dlang=eng&startitems=1&enditems=10.

But on the receiver it is not working. There is an empty list. 

This might be related (and it the outcome is similar) but in this case not using Docker or Bridge networks. This is just a simple port change in the Windows version.

**Comment by coffeegreg** [comment]
With query like this one :
> 13-5-2024 14:44:05 : Dbg : GET /setupapp/denon/asp/browsexm2/loginXML.asp?mac=0CEF23DA75BEE0D17F10B7F74274D2AF&fver=1.754333&dlang=eng&startitems=1&enditems=10.

AVR get root menu content with `My stations` (if enabled in `ytuner.ini`), `Radio browser` (if enabled in `ytuner.ini`) and `Bookmark` (if enabled in `ytuner.ini`). After that AVR try to reach YTuner web service via IP address. 
As I wrote earlier, now I see a reason why it would be good to add the ability to reach the YTuner web service using a different IP address and TCP port than the actual one belonging to the machine that runs the YTuner process, or use a domain name.
However, if the described problem is not related to what I am writing about, I will continue to think about how to solve it. :thinking:
Don't worry. :+1:

**Comment by coffeegreg** [comment]
Hi @Larsvb0.
Now, you can try new YTuner v1.2.3 and check out for a new `ActAsHost` parameter in `Configuration` section of `ytuner.ini` file.
Try to set this param to your proxy server IP address or just to `denon.vtuner.com` in your case. :rocket: 
Please let me know if this solved your problems.
Unfortunately, I do not have the opportunity to test new version of YTuner on any arm or arm64 (aarch64) platform at this moment.
If anyone has this opportunity, please test it. :+1:

**Comment by Larsvb0** [comment]
Hi @coffeegreg thanks for the update. I tried the Windows version to see if it works and unfortunately I do not think so.

Here is my setup

DNS runs on router 10.0.0.1, *.vtuner.com points to Reverse Proxy Server 10.0.0.10
Reverse Proxy on Server 10.0.0.10
Ytuner runs on NUC 10.0.0.12
I use a Denon x4100W

Only setting changed in tuner.ini = MessageInfoLevel=4

Reverse proxy on 10.0.0.10: denon.vtuner.com:80 to 10.0.0.12:80 - Ytuner default setting - works!
Reverse proxy on 10.0.0.10: denon.vtuner.com:80 to 10.0.0.12:80 - Ytuner WebServerPort=80 - works!
Reverse proxy on 10.0.0.10: denon.vtuner.com:80 to 10.0.0.12:8080 - Ytuner WebServerPort=8080 - Does not work, My Station 
takes very long time to load/hangs
Reverse proxy on 10.0.0.10: denon.vtuner.com:80 to 10.0.0.12:8080 - Ytuner WebServerPort=8080 ActAsHost=10.0.0.10 - Does not work, My Station show empty. 

Here is what I see in the logs:
-5-2024 19:52:31 : Inf : DNS Service: listening on: 10.0.0.12:53.
21-5-2024 19:52:31 : Inf : Web Service: listening on: 10.0.0.12:8080.
21-5-2024 19:52:31 : Inf : AVRs HTTP requests host target: 10.0.0.10.
21-5-2024 19:53:32 : Dbg : GET /setupapp/denon/asp/BrowseXML/loginXML.asp?token=0.
21-5-2024 19:53:32 : Dbg : GET /setupapp/denon/asp/browsexm2/loginXML.asp?mac=0CEF23DA75BEE0D17F10B7F74274D2AF&fver=1.754333&dlang=eng&startitems=1&enditems=10.
21-5-2024 19:53:32 : Dbg : GET /setupapp/denon/asp/browsexm2/loginXML.asp?mac=0CEF23DA75BEE0D17F10B7F74274D2AF&fver=1.754333&dlang=eng&startitems=1&enditems=10.

**Comment by coffeegreg** [comment]
That's great! I'm glad to know that work very well for you. :clap: 
I don't do projects like YTuner for money, but for people like you. :+1: 
Enjoy the sound of your Denon. :musical_note:
