### ISSUE TITLE
docker error: exec ./ytuner: exec format error

### ISSUE THREAD

**Issue by SimonBard** [coffeegreg/YTuner#38]
What is the filestructure within /app/host-shared of the docker container?
I get this error and I assume there is something wrong with my folderstructure.

~/Downloads/YTuner/YTuner-docker$ docker run --rm --network host -v ~/YTuner:/app/host-shared ytuner:1.2.2
exec ./ytuner: exec format error

This is my folderstructure:
```

├── config
└── YTuner-docker
    ├── Dockerfile
    ├── dockerfile.yaml
    ├── x86_64-linux
    │   ├── ytuner
    │   └── ytuner.ini
    └── ytuner-1.2.2-x86_64-linux.zip
```

In ytuner.ini, I used the default values, which means I did not adapt anything here.

**Comment by coffeegreg** [comment]
Hi @SimonBard 

`/app/host-shared` should contain all files whose content should remain persistent so that it is not lost when the app docker container terminates. Did you read this : https://github.com/coffeegreg/YTuner/blob/master/doc/DOCKER.md ?
In particular: 

>Edit and change the ytuner.ini file as you wish, but remember to set the following options :

>CacheFolderLocation=/app/host-shared
>ConfigFolderLocation=/app/host-shared
>DBFolderLocation=/app/host-shared

`exec format error` is probably related to docker and probably the wrong YTuner executable file (incorrect CPU arch and/or incorrect OS) you used in your container. Check your CPU arch, OS and bitwise (32/64).
Try to google `docker exec format error`. There are many answers related to your question. :+1:

**Comment by coffeegreg** [comment]
Closed due to inactivity.
